embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
mm_audio_weight: 0.1
aggr_mode: ['add']
reg_weight: 0

user_representation_size: 192
item_representation_size: 192

hyper_parameters: ["aggr_mode"]

